// Sample data for Divine-Nest Home Management Suite
// This file contains sample data for all 14 core tables
// Each table has 5 samples per category/subcategory as requested

export const sampleData = {
  issues: [
    // Emergency - External
    {
      id: 'issue-001',
      type: 'External',
      category: 'Emergency',
      sub_category: 'Medical Emergency',
      description: 'Father needs immediate medical attention - chest pain',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543210',
      preferred_resolution_date: '2024-01-15',
      assigned_to: 'Ambulance Service',
      status: 'Reported',
      created_by: 'Mother',
      created_at: '2024-01-15T10:30:00Z',
      updated_at: '2024-01-15T10:30:00Z'
    },
    {
      id: 'issue-002',
      type: 'External',
      category: 'Emergency',
      sub_category: 'Fire Emergency',
      description: 'Kitchen fire from gas stove malfunction',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '101',
      preferred_resolution_date: '2024-01-15',
      assigned_to: 'Fire Department',
      status: 'Resolved',
      created_by: 'Father',
      created_at: '2024-01-14T15:45:00Z',
      updated_at: '2024-01-14T16:15:00Z'
    },
    {
      id: 'issue-003',
      type: 'External',
      category: 'Emergency',
      sub_category: 'Electrical Emergency',
      description: 'Power outage in entire neighborhood',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '1912',
      preferred_resolution_date: '2024-01-16',
      assigned_to: 'Electricity Board',
      status: 'In Progress',
      created_by: 'Mother',
      created_at: '2024-01-15T20:00:00Z',
      updated_at: '2024-01-15T20:30:00Z'
    },
    {
      id: 'issue-004',
      type: 'External',
      category: 'Emergency',
      sub_category: 'Water Emergency',
      description: 'Burst water pipe flooding basement',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543211',
      preferred_resolution_date: '2024-01-16',
      assigned_to: 'Plumber',
      status: 'Assigned',
      created_by: 'Father',
      created_at: '2024-01-15T08:15:00Z',
      updated_at: '2024-01-15T09:00:00Z'
    },
    {
      id: 'issue-005',
      type: 'External',
      category: 'Emergency',
      sub_category: 'Security Emergency',
      description: 'Suspicious person spotted near house',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '100',
      preferred_resolution_date: '2024-01-15',
      assigned_to: 'Police',
      status: 'Resolved',
      created_by: 'Neighbor',
      created_at: '2024-01-14T22:30:00Z',
      updated_at: '2024-01-14T23:15:00Z'
    },

    // Urgents - Internal
    {
      id: 'issue-006',
      type: 'Internal',
      category: 'Urgents',
      sub_category: 'Child Health',
      description: 'Child has high fever and needs medication',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543212',
      preferred_resolution_date: '2024-01-16',
      assigned_to: 'Mother',
      status: 'In Progress',
      created_by: 'Father',
      created_at: '2024-01-15T14:20:00Z',
      updated_at: '2024-01-15T14:45:00Z'
    },
    {
      id: 'issue-007',
      type: 'Internal',
      category: 'Urgents',
      sub_category: 'Meal Preparation',
      description: 'Need to prepare lunch for unexpected guests',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543213',
      preferred_resolution_date: '2024-01-15',
      assigned_to: 'Mother',
      status: 'Resolved',
      created_by: 'Father',
      created_at: '2024-01-15T11:30:00Z',
      updated_at: '2024-01-15T13:00:00Z'
    },
    {
      id: 'issue-008',
      type: 'Internal',
      category: 'Urgents',
      sub_category: 'Transportation',
      description: 'Need pickup from school due to heavy rain',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: 'School Address, Coimbatore',
      contact: '+91-9876543214',
      preferred_resolution_date: '2024-01-15',
      assigned_to: 'Father',
      status: 'Resolved',
      created_by: 'School',
      created_at: '2024-01-15T15:00:00Z',
      updated_at: '2024-01-15T16:30:00Z'
    },
    {
      id: 'issue-009',
      type: 'Internal',
      category: 'Urgents',
      sub_category: 'Guest Accommodation',
      description: 'Relatives arriving tonight, need room preparation',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543215',
      preferred_resolution_date: '2024-01-15',
      assigned_to: 'Mother',
      status: 'In Progress',
      created_by: 'Father',
      created_at: '2024-01-15T18:00:00Z',
      updated_at: '2024-01-15T18:30:00Z'
    },
    {
      id: 'issue-010',
      type: 'Internal',
      category: 'Urgents',
      sub_category: 'Document Work',
      description: 'Need to complete bank paperwork urgently',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543216',
      preferred_resolution_date: '2024-01-17',
      assigned_to: 'Father',
      status: 'Assigned',
      created_by: 'Mother',
      created_at: '2024-01-15T09:15:00Z',
      updated_at: '2024-01-15T09:30:00Z'
    }
  ],

  requests: [
    // Emergency category
    {
      id: 'req-001',
      category: 'Emergency',
      sub_category: 'Medical',
      description: 'Request for home doctor visit for grandmother',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543217',
      preferred_resolution_date: '2024-01-16',
      assigned_to: 'Family Doctor',
      status: 'Reported',
      affected_audience: 'Grandmother',
      created_by: 'Daughter',
      created_at: '2024-01-15T10:00:00Z',
      updated_at: '2024-01-15T10:00:00Z'
    },
    {
      id: 'req-002',
      category: 'Emergency',
      sub_category: 'Security',
      description: 'Install additional security cameras',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543218',
      preferred_resolution_date: '2024-01-20',
      assigned_to: 'Security Company',
      status: 'Assigned',
      affected_audience: 'Entire Family',
      created_by: 'Father',
      created_at: '2024-01-14T16:30:00Z',
      updated_at: '2024-01-15T09:00:00Z'
    },
    {
      id: 'req-003',
      category: 'Emergency',
      sub_category: 'Electrical',
      description: 'Fix faulty wiring in kitchen',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543219',
      preferred_resolution_date: '2024-01-18',
      assigned_to: 'Electrician',
      status: 'In Progress',
      affected_audience: 'Kitchen Users',
      created_by: 'Mother',
      created_at: '2024-01-13T14:20:00Z',
      updated_at: '2024-01-15T11:00:00Z'
    },
    {
      id: 'req-004',
      category: 'Emergency',
      sub_category: 'Plumbing',
      description: 'Repair leaking bathroom faucet',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543220',
      preferred_resolution_date: '2024-01-17',
      assigned_to: 'Plumber',
      status: 'Reported',
      affected_audience: 'Bathroom Users',
      created_by: 'Father',
      created_at: '2024-01-15T08:45:00Z',
      updated_at: '2024-01-15T08:45:00Z'
    },
    {
      id: 'req-005',
      category: 'Emergency',
      sub_category: 'Roofing',
      description: 'Fix leaking roof during monsoon',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543221',
      preferred_resolution_date: '2024-01-19',
      assigned_to: 'Roofer',
      status: 'Assigned',
      affected_audience: 'Entire House',
      created_by: 'Mother',
      created_at: '2024-01-12T13:15:00Z',
      updated_at: '2024-01-14T10:30:00Z'
    },

    // Urgents category
    {
      id: 'req-006',
      category: 'Urgents',
      sub_category: 'Appliance Repair',
      description: 'Refrigerator not cooling properly',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543222',
      preferred_resolution_date: '2024-01-16',
      assigned_to: 'Appliance Technician',
      status: 'In Progress',
      affected_audience: 'Kitchen Users',
      created_by: 'Mother',
      created_at: '2024-01-14T11:30:00Z',
      updated_at: '2024-01-15T14:00:00Z'
    },
    {
      id: 'req-007',
      category: 'Urgents',
      sub_category: 'Cleaning Service',
      description: 'Deep cleaning before festival',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543223',
      preferred_resolution_date: '2024-01-18',
      assigned_to: 'Cleaning Service',
      status: 'Reported',
      affected_audience: 'Entire Family',
      created_by: 'Mother',
      created_at: '2024-01-15T09:20:00Z',
      updated_at: '2024-01-15T09:20:00Z'
    },
    {
      id: 'req-008',
      category: 'Urgents',
      sub_category: 'Pest Control',
      description: 'Ant infestation in kitchen',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543224',
      preferred_resolution_date: '2024-01-17',
      assigned_to: 'Pest Control Service',
      status: 'Assigned',
      affected_audience: 'Kitchen Users',
      created_by: 'Father',
      created_at: '2024-01-13T16:45:00Z',
      updated_at: '2024-01-14T08:30:00Z'
    },
    {
      id: 'req-009',
      category: 'Urgents',
      sub_category: 'Gardening',
      description: 'Trim overgrown plants',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543225',
      preferred_resolution_date: '2024-01-19',
      assigned_to: 'Gardener',
      status: 'Reported',
      affected_audience: 'Garden Users',
      created_by: 'Mother',
      created_at: '2024-01-15T07:30:00Z',
      updated_at: '2024-01-15T07:30:00Z'
    },
    {
      id: 'req-010',
      category: 'Urgents',
      sub_category: 'Vehicle Service',
      description: 'Car needs immediate servicing',
      location_lat: 11.0168,
      location_lng: 76.9558,
      location_address: '123 Main Street, Coimbatore',
      contact: '+91-9876543226',
      preferred_resolution_date: '2024-01-16',
      assigned_to: 'Car Workshop',
      status: 'In Progress',
      affected_audience: 'Family Drivers',
      created_by: 'Father',
      created_at: '2024-01-14T10:15:00Z',
      updated_at: '2024-01-15T12:00:00Z'
    }
  ],

  foods: [
    // Breakfast - South Indian
    {
      id: 'food-001',
      type: 'Breakfast',
      category: 'South Indian',
      sub_category: 'Idli',
      ingredients: 'Rice, Urad dal, Fenugreek seeds, Salt',
      preparation_stage: 'Soak rice and dal for 4 hours',
      mixing_stage: 'Grind to smooth batter',
      boiling_stage: 'Ferment overnight',
      ready_stage: 'Steam in idli molds for 10 minutes',
      schedule: 'Weekly',
      audience: 'Family',
      health_factor: 'High fiber, Low calorie',
      time_factor: '30 minutes preparation + 8 hours fermentation',
      cost_per_serving: 15,
      serving_definition: '2 idlis per person',
      aroma_factor: 'Neutral',
      taste_factor: 'Neutral',
      created_at: '2024-01-15T06:00:00Z'
    },
    {
      id: 'food-002',
      type: 'Breakfast',
      category: 'South Indian',
      sub_category: 'Dosa',
      ingredients: 'Rice, Urad dal, Fenugreek seeds, Salt, Oil',
      preparation_stage: 'Soak rice and dal for 6 hours',
      mixing_stage: 'Grind and ferment for 12 hours',
      boiling_stage: 'Heat griddle and spread batter',
      ready_stage: 'Cook until golden brown',
      schedule: 'Weekly',
      audience: 'Family',
      health_factor: 'Good protein, Fermented food',
      time_factor: '45 minutes preparation + 12 hours fermentation',
      cost_per_serving: 20,
      serving_definition: '2 dosas per person',
      aroma_factor: 'Neutral',
      taste_factor: 'Neutral',
      created_at: '2024-01-15T07:00:00Z'
    },
    {
      id: 'food-003',
      type: 'Breakfast',
      category: 'South Indian',
      sub_category: 'Pongal',
      ingredients: 'Rice, Moong dal, Ghee, Pepper, Cumin, Cashews',
      preparation_stage: 'Cook rice and dal together',
      mixing_stage: 'Add spices and ghee',
      boiling_stage: 'Cook until creamy consistency',
      ready_stage: 'Garnish with cashews',
      schedule: 'Weekly',
      audience: 'Family',
      health_factor: 'High protein, Comfort food',
      time_factor: '30 minutes',
      cost_per_serving: 25,
      serving_definition: '1 bowl per person',
      aroma_factor: 'Spicy',
      taste_factor: 'Spicy',
      created_at: '2024-01-15T08:00:00Z'
    },
    {
      id: 'food-004',
      type: 'Breakfast',
      category: 'South Indian',
      sub_category: 'Upma',
      ingredients: 'Semolina, Vegetables, Mustard seeds, Curry leaves, Oil',
      preparation_stage: 'Roast semolina lightly',
      mixing_stage: 'Sauté vegetables and spices',
      boiling_stage: 'Add water and semolina, cook until done',
      ready_stage: 'Serve hot',
      schedule: 'Daily',
      audience: 'Family',
      health_factor: 'Vegetable rich, Quick meal',
      time_factor: '20 minutes',
      cost_per_serving: 18,
      serving_definition: '1 bowl per person',
      aroma_factor: 'Spicy',
      taste_factor: 'Spicy',
      created_at: '2024-01-15T09:00:00Z'
    },
    {
      id: 'food-005',
      type: 'Breakfast',
      category: 'South Indian',
      sub_category: 'Poori',
      ingredients: 'Wheat flour, Oil, Water, Salt, Potato, Onion',
      preparation_stage: 'Make dough and rest',
      mixing_stage: 'Prepare potato filling',
      boiling_stage: 'Deep fry pooris',
      ready_stage: 'Serve with potato curry',
      schedule: 'Weekly',
      audience: 'Family',
      health_factor: 'Carb rich, Occasional treat',
      time_factor: '45 minutes',
      cost_per_serving: 22,
      serving_definition: '3 pooris per person',
      aroma_factor: 'Neutral',
      taste_factor: 'Neutral',
      created_at: '2024-01-15T10:00:00Z'
    },

    // Lunch - South Indian
    {
      id: 'food-006',
      type: 'Lunch',
      category: 'South Indian',
      sub_category: 'Sambar Rice',
      ingredients: 'Rice, Toor dal, Vegetables, Tamarind, Sambar powder',
      preparation_stage: 'Cook rice and dal separately',
      mixing_stage: 'Prepare sambar with vegetables',
      boiling_stage: 'Mix rice with sambar',
      ready_stage: 'Serve with papad and pickle',
      schedule: 'Weekly',
      audience: 'Family',
      health_factor: 'Balanced meal, High protein',
      time_factor: '45 minutes',
      cost_per_serving: 30,
      serving_definition: '1 plate per person',
      aroma_factor: 'Spicy',
      taste_factor: 'Spicy',
      created_at: '2024-01-15T12:00:00Z'
    },
    {
      id: 'food-007',
      type: 'Lunch',
      category: 'South Indian',
      sub_category: 'Rasam Rice',
      ingredients: 'Rice, Tamarind, Tomato, Rasam powder, Garlic',
      preparation_stage: 'Cook rice separately',
      mixing_stage: 'Prepare rasam with spices',
      boiling_stage: 'Boil rasam until frothy',
      ready_stage: 'Mix with rice and serve',
      schedule: 'Weekly',
      audience: 'Family',
      health_factor: 'Digestive, Light meal',
      time_factor: '30 minutes',
      cost_per_serving: 25,
      serving_definition: '1 plate per person',
      aroma_factor: 'Spicy',
      taste_factor: 'Sour',
      created_at: '2024-01-15T13:00:00Z'
    },
    {
      id: 'food-008',
      type: 'Lunch',
      category: 'South Indian',
      sub_category: 'Curd Rice',
      ingredients: 'Rice, Curd, Milk, Cucumber, Coriander',
      preparation_stage: 'Cook rice and cool',
      mixing_stage: 'Mix with curd and milk',
      boiling_stage: 'No boiling required',
      ready_stage: 'Add cucumber and serve',
      schedule: 'Daily',
      audience: 'Family',
      health_factor: 'Probiotic, Cooling food',
      time_factor: '15 minutes',
      cost_per_serving: 20,
      serving_definition: '1 bowl per person',
      aroma_factor: 'Neutral',
      taste_factor: 'Neutral',
      created_at: '2024-01-15T14:00:00Z'
    },
    {
      id: 'food-009',
      type: 'Lunch',
      category: 'South Indian',
      sub_category: 'Lemon Rice',
      ingredients: 'Rice, Lemon, Peanuts, Curry leaves, Turmeric',
      preparation_stage: 'Cook rice and cool',
      mixing_stage: 'Mix lemon juice and spices',
      boiling_stage: 'No boiling required',
      ready_stage: 'Add peanuts and serve',
      schedule: 'Weekly',
      audience: 'Family',
      health_factor: 'Vitamin C rich, Quick meal',
      time_factor: '20 minutes',
      cost_per_serving: 18,
      serving_definition: '1 plate per person',
      aroma_factor: 'Spicy',
      taste_factor: 'Sour',
      created_at: '2024-01-15T15:00:00Z'
    },
    {
      id: 'food-010',
      type: 'Lunch',
      category: 'South Indian',
      sub_category: 'Tomato Rice',
      ingredients: 'Rice, Tomato, Onion, Spices, Oil',
      preparation_stage: 'Cook rice separately',
      mixing_stage: 'Sauté tomatoes and spices',
      boiling_stage: 'Cook tomato mixture',
      ready_stage: 'Mix with rice and serve',
      schedule: 'Weekly',
      audience: 'Family',
      health_factor: 'Vitamin rich, Tangy flavor',
      time_factor: '25 minutes',
      cost_per_serving: 22,
      serving_definition: '1 plate per person',
      aroma_factor: 'Spicy',
      taste_factor: 'Sour',
      created_at: '2024-01-15T16:00:00Z'
    }
  ],

  inventory: [
    // Food Ingredient - Dry Goods
    {
      id: 'inv-001',
      type: 'Food Ingredient',
      category: 'Dry Goods',
      sub_category: 'Rice',
      quantity_available: 25,
      unit: 'kg',
      location: 'Kitchen Storage',
      restock_threshold: 5,
      preferred_vendor: 'Local Rice Mill',
      last_updated: '2024-01-15T10:00:00Z',
      added_by: 'Mother',
      created_at: '2024-01-01T10:00:00Z'
    },
    {
      id: 'inv-002',
      type: 'Food Ingredient',
      category: 'Dry Goods',
      sub_category: 'Wheat Flour',
      quantity_available: 10,
      unit: 'kg',
      location: 'Kitchen Storage',
      restock_threshold: 2,
      preferred_vendor: 'Super Market',
      last_updated: '2024-01-14T15:30:00Z',
      added_by: 'Mother',
      created_at: '2024-01-05T11:00:00Z'
    },
    {
      id: 'inv-003',
      type: 'Food Ingredient',
      category: 'Dry Goods',
      sub_category: 'Sugar',
      quantity_available: 8,
      unit: 'kg',
      location: 'Kitchen Pantry',
      restock_threshold: 1,
      preferred_vendor: 'Wholesale Store',
      last_updated: '2024-01-13T09:15:00Z',
      added_by: 'Father',
      created_at: '2024-01-03T14:20:00Z'
    },
    {
      id: 'inv-004',
      type: 'Food Ingredient',
      category: 'Dry Goods',
      sub_category: 'Salt',
      quantity_available: 5,
      unit: 'kg',
      location: 'Kitchen Storage',
      restock_threshold: 1,
      preferred_vendor: 'Local Store',
      last_updated: '2024-01-12T16:45:00Z',
      added_by: 'Mother',
      created_at: '2024-01-02T13:30:00Z'
    },
    {
      id: 'inv-005',
      type: 'Food Ingredient',
      category: 'Dry Goods',
      sub_category: 'Tea Powder',
      quantity_available: 2,
      unit: 'kg',
      location: 'Kitchen Pantry',
      restock_threshold: 0.5,
      preferred_vendor: 'Tea Shop',
      last_updated: '2024-01-11T08:20:00Z',
      added_by: 'Father',
      created_at: '2024-01-04T10:15:00Z'
    },

    // Grocery - Fresh Produce
    {
      id: 'inv-006',
      type: 'Grocery',
      category: 'Fresh Produce',
      sub_category: 'Tomatoes',
      quantity_available: 12,
      unit: 'pieces',
      location: 'Refrigerator',
      restock_threshold: 6,
      preferred_vendor: 'Local Market',
      last_updated: '2024-01-15T07:30:00Z',
      added_by: 'Mother',
      created_at: '2024-01-14T18:00:00Z'
    },
    {
      id: 'inv-007',
      type: 'Grocery',
      category: 'Fresh Produce',
      sub_category: 'Onions',
      quantity_available: 20,
      unit: 'pieces',
      location: 'Kitchen Basket',
      restock_threshold: 10,
      preferred_vendor: 'Vegetable Vendor',
      last_updated: '2024-01-14T19:45:00Z',
      added_by: 'Mother',
      created_at: '2024-01-13T16:30:00Z'
    },
    {
      id: 'inv-008',
      type: 'Grocery',
      category: 'Fresh Produce',
      sub_category: 'Potatoes',
      quantity_available: 15,
      unit: 'kg',
      location: 'Kitchen Storage',
      restock_threshold: 5,
      preferred_vendor: 'Farm Fresh',
      last_updated: '2024-01-13T14:20:00Z',
      added_by: 'Father',
      created_at: '2024-01-12T11:15:00Z'
    },
    {
      id: 'inv-009',
      type: 'Grocery',
      category: 'Fresh Produce',
      sub_category: 'Green Chillies',
      quantity_available: 100,
      unit: 'pieces',
      location: 'Refrigerator',
      restock_threshold: 50,
      preferred_vendor: 'Local Market',
      last_updated: '2024-01-15T08:00:00Z',
      added_by: 'Mother',
      created_at: '2024-01-14T17:30:00Z'
    },
    {
      id: 'inv-010',
      type: 'Grocery',
      category: 'Fresh Produce',
      sub_category: 'Coriander Leaves',
      quantity_available: 5,
      unit: 'packets',
      location: 'Refrigerator',
      restock_threshold: 2,
      preferred_vendor: 'Vegetable Vendor',
      last_updated: '2024-01-14T20:15:00Z',
      added_by: 'Mother',
      created_at: '2024-01-14T10:45:00Z'
    }
  ],

  tasks: [
    // Duty - Self
    {
      id: 'task-001',
      type: 'Duty',
      category: 'Self',
      sub_category: 'Personal Hygiene',
      description: 'Morning bath and personal grooming routine',
      assigned_to: 'Self',
      mandatory: true,
      frequency: 'Daily',
      panchangam_link: null,
      time_of_day: 'Morning',
      location: 'Bathroom',
      due_date: null,
      alert_type: 'ToDo',
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'task-002',
      type: 'Duty',
      category: 'Self',
      sub_category: 'Exercise',
      description: 'Daily morning walk or yoga practice',
      assigned_to: 'Self',
      mandatory: false,
      frequency: 'Daily',
      panchangam_link: null,
      time_of_day: 'Morning',
      location: 'Garden/Park',
      due_date: null,
      alert_type: 'Reminder',
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'task-003',
      type: 'Duty',
      category: 'Self',
      sub_category: 'Meditation',
      description: 'Daily meditation and prayer time',
      assigned_to: 'Self',
      mandatory: true,
      frequency: 'Daily',
      panchangam_link: 'Morning Prayers',
      time_of_day: 'Morning',
      location: 'Pooja Room',
      due_date: null,
      alert_type: 'Alarm',
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'task-004',
      type: 'Duty',
      category: 'Self',
      sub_category: 'Learning',
      description: 'Read spiritual texts or educational material',
      assigned_to: 'Self',
      mandatory: false,
      frequency: 'Daily',
      panchangam_link: null,
      time_of_day: 'Evening',
      location: 'Study Room',
      due_date: null,
      alert_type: 'Notes',
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'task-005',
      type: 'Duty',
      category: 'Self',
      sub_category: 'Health Check',
      description: 'Monitor blood pressure and basic health parameters',
      assigned_to: 'Self',
      mandatory: true,
      frequency: 'Daily',
      panchangam_link: null,
      time_of_day: 'Morning',
      location: 'Living Room',
      due_date: null,
      alert_type: 'ToDo',
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },

    // Responsibility - Family
    {
      id: 'task-006',
      type: 'Responsibility',
      category: 'Family',
      sub_category: 'Children Care',
      description: 'Help children with homework and studies',
      assigned_to: 'Parents',
      mandatory: true,
      frequency: 'Daily',
      panchangam_link: null,
      time_of_day: 'Evening',
      location: 'Study Room',
      due_date: null,
      alert_type: 'ToDo',
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'task-007',
      type: 'Responsibility',
      category: 'Family',
      sub_category: 'Elder Care',
      description: 'Attend to elderly family members needs',
      assigned_to: 'Adult Children',
      mandatory: true,
      frequency: 'Daily',
      panchangam_link: null,
      time_of_day: 'Morning',
      location: 'Various',
      due_date: null,
      alert_type: 'Reminder',
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'task-008',
      type: 'Responsibility',
      category: 'Family',
      sub_category: 'Meal Preparation',
      description: 'Prepare nutritious meals for family',
      assigned_to: 'Mother/Cook',
      mandatory: true,
      frequency: 'Daily',
      panchangam_link: null,
      time_of_day: 'Morning',
      location: 'Kitchen',
      due_date: null,
      alert_type: 'Alarm',
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'task-009',
      type: 'Responsibility',
      category: 'Family',
      sub_category: 'House Cleaning',
      description: 'Maintain cleanliness of living spaces',
      assigned_to: 'Family Members',
      mandatory: true,
      frequency: 'Daily',
      panchangam_link: null,
      time_of_day: 'Morning',
      location: 'Various',
      due_date: null,
      alert_type: 'ToDo',
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'task-010',
      type: 'Responsibility',
      category: 'Family',
      sub_category: 'Financial Planning',
      description: 'Review and plan family finances',
      assigned_to: 'Father',
      mandatory: true,
      frequency: 'Monthly',
      panchangam_link: null,
      time_of_day: 'Evening',
      location: 'Study Room',
      due_date: null,
      alert_type: 'Notes',
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    }
  ],

  activities: [
    // Physical - Learning
    {
      id: 'act-001',
      type: 'Physical',
      category: 'Learning',
      sub_category: 'Yoga',
      description: 'Practice yoga asanas for physical and mental wellness',
      participant: 'Family Members',
      frequency: 'Daily',
      location: 'Garden',
      time_of_day: 'Morning',
      alert_type: 'Reminder',
      created_by: 'Mother',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'act-002',
      type: 'Physical',
      category: 'Learning',
      sub_category: 'Martial Arts',
      description: 'Learn self-defense techniques',
      participant: 'Children',
      frequency: 'Weekly',
      location: 'Dojo',
      time_of_day: 'Afternoon',
      alert_type: 'Alarm',
      created_by: 'Father',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'act-003',
      type: 'Physical',
      category: 'Learning',
      sub_category: 'Dance',
      description: 'Learn traditional Bharatanatyam dance',
      participant: 'Daughter',
      frequency: 'Weekly',
      location: 'Dance Class',
      time_of_day: 'Evening',
      alert_type: 'Reminder',
      created_by: 'Mother',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'act-004',
      type: 'Physical',
      category: 'Learning',
      sub_category: 'Music',
      description: 'Learn Carnatic music vocals',
      participant: 'Son',
      frequency: 'Weekly',
      location: 'Music Class',
      time_of_day: 'Afternoon',
      alert_type: 'Alarm',
      created_by: 'Father',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'act-005',
      type: 'Physical',
      category: 'Learning',
      sub_category: 'Art',
      description: 'Painting and sketching classes',
      participant: 'Children',
      frequency: 'Weekly',
      location: 'Art Studio',
      time_of_day: 'Afternoon',
      alert_type: 'Reminder',
      created_by: 'Mother',
      created_at: '2024-01-01T00:00:00Z'
    },

    // Mental - Crafting
    {
      id: 'act-006',
      type: 'Mental',
      category: 'Crafting',
      sub_category: 'Knitting',
      description: 'Knit sweaters and accessories for family',
      participant: 'Mother',
      frequency: 'Daily',
      location: 'Living Room',
      time_of_day: 'Evening',
      alert_type: 'None',
      created_by: 'Mother',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'act-007',
      type: 'Mental',
      category: 'Crafting',
      sub_category: 'Cooking',
      description: 'Experiment with new recipes',
      participant: 'Mother',
      frequency: 'Weekly',
      location: 'Kitchen',
      time_of_day: 'Afternoon',
      alert_type: 'Reminder',
      created_by: 'Mother',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'act-008',
      type: 'Mental',
      category: 'Crafting',
      sub_category: 'Gardening',
      description: 'Maintain home garden and grow vegetables',
      participant: 'Father',
      frequency: 'Daily',
      location: 'Garden',
      time_of_day: 'Morning',
      alert_type: 'None',
      created_by: 'Father',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'act-009',
      type: 'Mental',
      category: 'Crafting',
      sub_category: 'Woodworking',
      description: 'Build furniture and home decor items',
      participant: 'Father',
      frequency: 'Weekly',
      location: 'Workshop',
      time_of_day: 'Afternoon',
      alert_type: 'Reminder',
      created_by: 'Father',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'act-010',
      type: 'Mental',
      category: 'Crafting',
      sub_category: 'Photography',
      description: 'Capture family moments and events',
      participant: 'Son',
      frequency: 'Ad-Hoc',
      location: 'Various',
      time_of_day: 'Afternoon',
      alert_type: 'None',
      created_by: 'Son',
      created_at: '2024-01-01T00:00:00Z'
    }
  ],

  finance: [
    // Budget - Monthly
    {
      id: 'fin-001',
      type: 'Budget',
      category: 'Household',
      sub_category: 'Groceries',
      amount: 15000,
      recurring: 'By Period (Fixed)',
      date: '2024-01-01',
      actor: 'Mother',
      source: 'Manual',
      notes: 'Monthly grocery budget for family of 4',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fin-002',
      type: 'Budget',
      category: 'Utilities',
      sub_category: 'Electricity',
      amount: 3000,
      recurring: 'By Period (Fixed)',
      date: '2024-01-01',
      actor: 'Father',
      source: 'Manual',
      notes: 'Monthly electricity bill estimate',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fin-003',
      type: 'Budget',
      category: 'Education',
      sub_category: 'School Fees',
      amount: 25000,
      recurring: 'By Period (Fixed)',
      date: '2024-01-01',
      actor: 'Father',
      source: 'Manual',
      notes: 'Quarterly school fees for children',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fin-004',
      type: 'Budget',
      category: 'Healthcare',
      sub_category: 'Medical',
      amount: 10000,
      recurring: 'By Period (Flexible)',
      date: '2024-01-01',
      actor: 'Mother',
      source: 'Manual',
      notes: 'Emergency medical fund',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fin-005',
      type: 'Budget',
      category: 'Transportation',
      sub_category: 'Fuel',
      amount: 5000,
      recurring: 'By Period (Fixed)',
      date: '2024-01-01',
      actor: 'Father',
      source: 'Manual',
      notes: 'Monthly fuel expenses',
      created_at: '2024-01-01T00:00:00Z'
    },

    // Income - Salary
    {
      id: 'fin-006',
      type: 'Income',
      category: 'Salary',
      sub_category: 'Primary Job',
      amount: 75000,
      recurring: 'By Period (Fixed)',
      date: '2024-01-01',
      actor: 'Father',
      source: 'Manual',
      notes: 'Monthly salary from IT company',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fin-007',
      type: 'Income',
      category: 'Salary',
      sub_category: 'Part-time Teaching',
      amount: 15000,
      recurring: 'By Period (Fixed)',
      date: '2024-01-01',
      actor: 'Mother',
      source: 'Manual',
      notes: 'Monthly income from tuition classes',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fin-008',
      type: 'Income',
      category: 'Investment',
      sub_category: 'Interest',
      amount: 2500,
      recurring: 'By Period (Fixed)',
      date: '2024-01-01',
      actor: 'Father',
      source: 'Manual',
      notes: 'Monthly FD interest',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fin-009',
      type: 'Income',
      category: 'Business',
      sub_category: 'Rental Income',
      amount: 12000,
      recurring: 'By Period (Fixed)',
      date: '2024-01-01',
      actor: 'Father',
      source: 'Manual',
      notes: 'Monthly rental from commercial property',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fin-010',
      type: 'Income',
      category: 'Other',
      sub_category: 'Gifts',
      amount: 5000,
      recurring: 'None',
      date: '2024-01-15',
      actor: 'Relatives',
      source: 'Manual',
      notes: 'Festival gift money',
      created_at: '2024-01-15T00:00:00Z'
    }
  ],

  rewards: [
    // Child - Star
    {
      id: 'rew-001',
      person: 'Arjun',
      role: 'Child',
      type: 'Star',
      reason: 'Completed homework without reminders',
      points: 5,
      date: '2024-01-15',
      created_at: '2024-01-15T18:00:00Z'
    },
    {
      id: 'rew-002',
      person: 'Priya',
      role: 'Child',
      type: 'Star',
      reason: 'Helped mother in kitchen',
      points: 3,
      date: '2024-01-14',
      created_at: '2024-01-14T19:30:00Z'
    },
    {
      id: 'rew-003',
      person: 'Arjun',
      role: 'Child',
      type: 'Star',
      reason: 'Scored 95% in mathematics test',
      points: 10,
      date: '2024-01-13',
      created_at: '2024-01-13T17:00:00Z'
    },
    {
      id: 'rew-004',
      person: 'Priya',
      role: 'Child',
      type: 'Star',
      reason: 'Practiced music for 1 hour',
      points: 4,
      date: '2024-01-12',
      created_at: '2024-01-12T20:15:00Z'
    },
    {
      id: 'rew-005',
      person: 'Arjun',
      role: 'Child',
      type: 'Star',
      reason: 'Cleaned his room without being asked',
      points: 3,
      date: '2024-01-11',
      created_at: '2024-01-11T16:45:00Z'
    },

    // Adult - Karma
    {
      id: 'rew-006',
      person: 'Ravi Kumar',
      role: 'Adult',
      type: 'Karma',
      reason: 'Volunteered at temple festival',
      points: 15,
      date: '2024-01-10',
      created_at: '2024-01-10T14:30:00Z'
    },
    {
      id: 'rew-007',
      person: 'Lakshmi Ravi',
      role: 'Adult',
      type: 'Karma',
      reason: 'Donated to charity',
      points: 20,
      date: '2024-01-09',
      created_at: '2024-01-09T11:20:00Z'
    },
    {
      id: 'rew-008',
      person: 'Ravi Kumar',
      role: 'Adult',
      type: 'Karma',
      reason: 'Helped neighbor in medical emergency',
      points: 25,
      date: '2024-01-08',
      created_at: '2024-01-08T09:15:00Z'
    },
    {
      id: 'rew-009',
      person: 'Lakshmi Ravi',
      role: 'Adult',
      type: 'Karma',
      reason: 'Organized community prayer meeting',
      points: 18,
      date: '2024-01-07',
      created_at: '2024-01-07T15:45:00Z'
    },
    {
      id: 'rew-010',
      person: 'Ravi Kumar',
      role: 'Adult',
      type: 'Karma',
      reason: 'Mentored youth in career guidance',
      points: 12,
      date: '2024-01-06',
      created_at: '2024-01-06T13:30:00Z'
    }
  ],

  assets: [
    // Documents - Personal
    {
      id: 'asset-001',
      category: 'Documents',
      sub_category: 'ID Proof',
      name: 'Aadhaar Card - Ravi Kumar',
      description: 'Primary identity document',
      location: 'Safe Box',
      owner: 'Ravi Kumar',
      date_added: '2020-01-15',
      tags: '["identity", "government", "personal"]',
      created_at: '2020-01-15T00:00:00Z'
    },
    {
      id: 'asset-002',
      category: 'Documents',
      sub_category: 'Certificates',
      name: 'Marriage Certificate',
      description: 'Marriage certificate of Ravi and Lakshmi',
      location: 'Safe Box',
      owner: 'Family',
      date_added: '2015-03-20',
      tags: '["marriage", "legal", "family"]',
      created_at: '2015-03-20T00:00:00Z'
    },
    {
      id: 'asset-003',
      category: 'Documents',
      sub_category: 'Property',
      name: 'House Deed',
      description: 'Deed for residential property',
      location: 'Bank Locker',
      owner: 'Ravi Kumar',
      date_added: '2018-06-10',
      tags: '["property", "legal", "valuable"]',
      created_at: '2018-06-10T00:00:00Z'
    },
    {
      id: 'asset-004',
      category: 'Documents',
      sub_category: 'Education',
      name: 'Degree Certificates',
      description: 'University degrees and diplomas',
      location: 'File Cabinet',
      owner: 'Ravi Kumar',
      date_added: '2005-05-15',
      tags: '["education", "qualification", "career"]',
      created_at: '2005-05-15T00:00:00Z'
    },
    {
      id: 'asset-005',
      category: 'Documents',
      sub_category: 'Insurance',
      name: 'Life Insurance Policies',
      description: 'Term life and investment policies',
      location: 'Safe Box',
      owner: 'Ravi Kumar',
      date_added: '2019-08-22',
      tags: '["insurance", "financial", "protection"]',
      created_at: '2019-08-22T00:00:00Z'
    },

    // Photos - Family
    {
      id: 'asset-006',
      category: 'Photos',
      sub_category: 'Wedding',
      name: 'Wedding Album 2015',
      description: 'Complete wedding photo collection',
      location: 'Living Room Shelf',
      owner: 'Family',
      date_added: '2015-03-20',
      tags: '["wedding", "family", "memories"]',
      created_at: '2015-03-20T00:00:00Z'
    },
    {
      id: 'asset-007',
      category: 'Photos',
      sub_category: 'Children',
      name: 'Baby Photos - Arjun',
      description: 'First year photos of son',
      location: 'Bedroom Album',
      owner: 'Lakshmi Ravi',
      date_added: '2016-11-15',
      tags: '["children", "baby", "memories"]',
      created_at: '2016-11-15T00:00:00Z'
    },
    {
      id: 'asset-008',
      category: 'Photos',
      sub_category: 'Festivals',
      name: 'Pongal Celebration 2023',
      description: 'Family photos during Pongal festival',
      location: 'Digital Storage',
      owner: 'Family',
      date_added: '2023-01-15',
      tags: '["festival", "pongal", "tradition"]',
      created_at: '2023-01-15T00:00:00Z'
    },
    {
      id: 'asset-009',
      category: 'Photos',
      sub_category: 'Vacation',
      name: 'Kerala Trip 2022',
      description: 'Family vacation photos',
      location: 'Digital Storage',
      owner: 'Family',
      date_added: '2022-12-20',
      tags: '["vacation", "travel", "memories"]',
      created_at: '2022-12-20T00:00:00Z'
    },
    {
      id: 'asset-010',
      category: 'Photos',
      sub_category: 'Graduation',
      name: 'Priya School Graduation',
      description: 'Daughter graduation ceremony photos',
      location: 'Living Room Shelf',
      owner: 'Family',
      date_added: '2023-05-10',
      tags: '["graduation", "achievement", "children"]',
      created_at: '2023-05-10T00:00:00Z'
    }
  ],

  family: [
    // Nuclear - Profile
    {
      id: 'fam-001',
      type: 'Nuclear',
      category: 'Profile',
      sub_category: 'Members',
      title: 'Ravi Kumar - Family Head',
      description: 'Software engineer, age 45, responsible for family finances and major decisions',
      date_time: '1980-03-15T00:00:00Z',
      location: 'Coimbatore, Tamil Nadu',
      media_type: 'Blog',
      media_url: null,
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fam-002',
      type: 'Nuclear',
      category: 'Profile',
      sub_category: 'Members',
      title: 'Lakshmi Ravi - Homemaker',
      description: 'Dedicated mother and wife, age 42, manages household and children education',
      date_time: '1982-07-22T00:00:00Z',
      location: 'Coimbatore, Tamil Nadu',
      media_type: 'Blog',
      media_url: null,
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fam-003',
      type: 'Nuclear',
      category: 'Profile',
      sub_category: 'Members',
      title: 'Arjun Ravi - Son',
      description: 'Class 10 student, age 15, interested in cricket and mathematics',
      date_time: '2009-01-10T00:00:00Z',
      location: 'Coimbatore, Tamil Nadu',
      media_type: 'Blog',
      media_url: null,
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fam-004',
      type: 'Nuclear',
      category: 'Profile',
      sub_category: 'Members',
      title: 'Priya Ravi - Daughter',
      description: 'Class 8 student, age 13, talented in music and dance',
      date_time: '2011-05-08T00:00:00Z',
      location: 'Coimbatore, Tamil Nadu',
      media_type: 'Blog',
      media_url: null,
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'fam-005',
      type: 'Nuclear',
      category: 'Profile',
      sub_category: 'Members',
      title: 'Grandmother - Lakshmi\'s Mother',
      description: 'Elderly family member, age 72, lives with family, spiritual guide',
      date_time: '1952-11-30T00:00:00Z',
      location: 'Coimbatore, Tamil Nadu',
      media_type: 'Blog',
      media_url: null,
      created_by: 'System',
      created_at: '2024-01-01T00:00:00Z'
    },

    // Nuclear - Wisdom
    {
      id: 'fam-006',
      type: 'Nuclear',
      category: 'Wisdom',
      sub_category: 'Life Lessons',
      title: 'The Importance of Family Unity',
      description: 'Grandmother shares wisdom about maintaining family bonds through thick and thin',
      date_time: '2024-01-10T18:00:00Z',
      location: 'Living Room',
      media_type: 'Audio',
      media_url: 'audio/family-unity-lesson.mp3',
      created_by: 'Grandmother',
      created_at: '2024-01-10T18:00:00Z'
    },
    {
      id: 'fam-007',
      type: 'Nuclear',
      category: 'Wisdom',
      sub_category: 'Life Lessons',
      title: 'Value of Education',
      description: 'Father shares experiences about importance of education in life',
      date_time: '2024-01-08T20:30:00Z',
      location: 'Study Room',
      media_type: 'Video',
      media_url: 'video/education-importance.mp4',
      created_by: 'Father',
      created_at: '2024-01-08T20:30:00Z'
    },
    {
      id: 'fam-008',
      type: 'Nuclear',
      category: 'Wisdom',
      sub_category: 'Life Lessons',
      title: 'Spiritual Discipline',
      description: 'Mother teaches about maintaining daily spiritual practices',
      date_time: '2024-01-05T06:00:00Z',
      location: 'Pooja Room',
      media_type: 'Blog',
      media_url: null,
      created_by: 'Mother',
      created_at: '2024-01-05T06:00:00Z'
    },
    {
      id: 'fam-009',
      type: 'Nuclear',
      category: 'Wisdom',
      sub_category: 'Life Lessons',
      title: 'Financial Responsibility',
      description: 'Father explains principles of money management and saving',
      date_time: '2024-01-03T19:15:00Z',
      location: 'Living Room',
      media_type: 'Audio',
      media_url: 'audio/financial-responsibility.mp3',
      created_by: 'Father',
      created_at: '2024-01-03T19:15:00Z'
    },
    {
      id: 'fam-010',
      type: 'Nuclear',
      category: 'Wisdom',
      sub_category: 'Life Lessons',
      title: 'Respect for Elders',
      description: 'Family discussion on traditional values and respecting elders',
      date_time: '2024-01-01T17:45:00Z',
      location: 'Dining Room',
      media_type: 'Blog',
      media_url: null,
      created_by: 'Grandmother',
      created_at: '2024-01-01T17:45:00Z'
    }
  ],

  ai_prompts: [
    // Alert - SMS
    {
      id: 'ai-001',
      type: 'Alert',
      category: 'SMS',
      purpose: 'Morning wake up call',
      trigger_time: '06:00:00',
      trigger_location_lat: null,
      trigger_location_lng: null,
      trigger_radius_meters: null,
      frequency: 'Daily',
      sound_type: 'Pleasant',
      volume_level: 'Medium',
      conditions: 'Weekdays only',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'ai-002',
      type: 'Alert',
      category: 'SMS',
      purpose: 'School pickup reminder',
      trigger_time: '15:30:00',
      trigger_location_lat: null,
      trigger_location_lng: null,
      trigger_radius_meters: null,
      frequency: 'Daily',
      sound_type: 'Positive',
      volume_level: 'High',
      conditions: 'School days only',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'ai-003',
      type: 'Alert',
      category: 'SMS',
      purpose: 'Medicine reminder',
      trigger_time: '20:00:00',
      trigger_location_lat: null,
      trigger_location_lng: null,
      trigger_radius_meters: null,
      frequency: 'Daily',
      sound_type: 'Pleasant',
      volume_level: 'Medium',
      conditions: 'For grandmother',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'ai-004',
      type: 'Alert',
      category: 'SMS',
      purpose: 'Prayer time reminder',
      trigger_time: '18:00:00',
      trigger_location_lat: null,
      trigger_location_lng: null,
      trigger_radius_meters: null,
      frequency: 'Daily',
      sound_type: 'Positive',
      volume_level: 'Low',
      conditions: 'Evening prayers',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'ai-005',
      type: 'Alert',
      category: 'SMS',
      purpose: 'Water plants reminder',
      trigger_time: '07:00:00',
      trigger_location_lat: null,
      trigger_location_lng: null,
      trigger_radius_meters: null,
      frequency: 'Daily',
      sound_type: 'Pleasant',
      volume_level: 'Medium',
      conditions: 'Garden maintenance',
      created_at: '2024-01-01T00:00:00Z'
    },

    // Notes - Email
    {
      id: 'ai-006',
      type: 'Notes',
      category: 'Email',
      purpose: 'Weekly meal plan summary',
      trigger_time: '09:00:00',
      trigger_location_lat: null,
      trigger_location_lng: null,
      trigger_radius_meters: null,
      frequency: 'Weekly',
      sound_type: 'Neutral',
      volume_level: 'Low',
      conditions: 'Every Monday',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'ai-007',
      type: 'Notes',
      category: 'Email',
      purpose: 'Monthly expense report',
      trigger_time: '10:00:00',
      trigger_location_lat: null,
      trigger_location_lng: null,
      trigger_radius_meters: null,
      frequency: 'Monthly',
      sound_type: 'Neutral',
      volume_level: 'Low',
      conditions: 'First day of month',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'ai-008',
      type: 'Notes',
      category: 'Email',
      purpose: 'Children progress report',
      trigger_time: '19:00:00',
      trigger_location_lat: null,
      trigger_location_lng: null,
      trigger_radius_meters: null,
      frequency: 'Weekly',
      sound_type: 'Positive',
      volume_level: 'Medium',
      conditions: 'Every Friday',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'ai-009',
      type: 'Notes',
      category: 'Email',
      purpose: 'Health check reminders',
      trigger_time: '08:00:00',
      trigger_location_lat: null,
      trigger_location_lng: null,
      trigger_radius_meters: null,
      frequency: 'Weekly',
      sound_type: 'Pleasant',
      volume_level: 'Medium',
      conditions: 'Health monitoring',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'ai-010',
      type: 'Notes',
      category: 'Email',
      purpose: 'Festival preparation checklist',
      trigger_time: '12:00:00',
      trigger_location_lat: null,
      trigger_location_lng: null,
      trigger_radius_meters: null,
      frequency: 'Custom',
      sound_type: 'Positive',
      volume_level: 'Medium',
      conditions: '7 days before festival',
      created_at: '2024-01-01T00:00:00Z'
    }
  ],

  users: [
    {
      id: 'user-001',
      role: 'Father',
      name: 'Ravi Kumar',
      nick_name: 'Appa',
      email: 'ravi.kumar@email.com',
      location: 'Coimbatore, Tamil Nadu',
      joined_date: '2020-01-15',
      picture_url: 'images/ravi-profile.jpg',
      auth_provider: 'Google',
      created_at: '2020-01-15T00:00:00Z'
    },
    {
      id: 'user-002',
      role: 'Mother',
      name: 'Lakshmi Ravi',
      nick_name: 'Amma',
      email: 'lakshmi.ravi@email.com',
      location: 'Coimbatore, Tamil Nadu',
      joined_date: '2020-01-15',
      picture_url: 'images/lakshmi-profile.jpg',
      auth_provider: 'Manual',
      created_at: '2020-01-15T00:00:00Z'
    },
    {
      id: 'user-003',
      role: 'Child',
      name: 'Arjun Ravi',
      nick_name: 'Arjun',
      email: 'arjun.ravi@email.com',
      location: 'Coimbatore, Tamil Nadu',
      joined_date: '2020-06-01',
      picture_url: 'images/arjun-profile.jpg',
      auth_provider: 'Manual',
      created_at: '2020-06-01T00:00:00Z'
    },
    {
      id: 'user-004',
      role: 'Child',
      name: 'Priya Ravi',
      nick_name: 'Priya',
      email: 'priya.ravi@email.com',
      location: 'Coimbatore, Tamil Nadu',
      joined_date: '2020-08-15',
      picture_url: 'images/priya-profile.jpg',
      auth_provider: 'Manual',
      created_at: '2020-08-15T00:00:00Z'
    },
    {
      id: 'user-005',
      role: 'Grandparent',
      name: 'Lakshmi Ammal',
      nick_name: 'Paati',
      email: 'lakshmi.ammal@email.com',
      location: 'Coimbatore, Tamil Nadu',
      joined_date: '2020-01-15',
      picture_url: 'images/paati-profile.jpg',
      auth_provider: 'Manual',
      created_at: '2020-01-15T00:00:00Z'
    }
  ],

  alerts: [
    // SMS alerts
    {
      id: 'alert-001',
      type: 'SMS',
      recipient: '+91-9876543210',
      message: 'Good morning! Time for morning prayers and breakfast preparation.',
      related_table: 'tasks',
      related_id: 'task-003',
      trigger_time: '2024-01-16T06:00:00Z',
      sent_at: null,
      status: 'Pending',
      created_at: '2024-01-15T10:00:00Z'
    },
    {
      id: 'alert-002',
      type: 'SMS',
      recipient: '+91-9876543211',
      message: 'Reminder: School pickup time in 30 minutes.',
      related_table: 'tasks',
      related_id: 'task-006',
      trigger_time: '2024-01-16T15:30:00Z',
      sent_at: null,
      status: 'Pending',
      created_at: '2024-01-15T11:00:00Z'
    },
    {
      id: 'alert-003',
      type: 'SMS',
      recipient: '+91-9876543212',
      message: 'Medicine time: Please take your evening medication.',
      related_table: 'tasks',
      related_id: 'task-005',
      trigger_time: '2024-01-16T20:00:00Z',
      sent_at: null,
      status: 'Pending',
      created_at: '2024-01-15T12:00:00Z'
    },
    {
      id: 'alert-004',
      type: 'SMS',
      recipient: '+91-9876543213',
      message: 'Festival reminder: Pongal preparations start tomorrow.',
      related_table: 'activities',
      related_id: 'act-008',
      trigger_time: '2024-01-16T18:00:00Z',
      sent_at: null,
      status: 'Pending',
      created_at: '2024-01-15T13:00:00Z'
    },
    {
      id: 'alert-005',
      type: 'SMS',
      recipient: '+91-9876543214',
      message: 'Inventory alert: Rice stock is low. Please restock.',
      related_table: 'inventory',
      related_id: 'inv-001',
      trigger_time: '2024-01-16T09:00:00Z',
      sent_at: null,
      status: 'Pending',
      created_at: '2024-01-15T14:00:00Z'
    },

    // WhatsApp alerts
    {
      id: 'alert-006',
      type: 'WhatsApp',
      recipient: '+91-9876543215',
      message: 'Family meeting: Please join us for dinner discussion tonight.',
      related_table: 'family',
      related_id: 'fam-010',
      trigger_time: '2024-01-16T19:30:00Z',
      sent_at: null,
      status: 'Pending',
      created_at: '2024-01-15T15:00:00Z'
    },
    {
      id: 'alert-007',
      type: 'WhatsApp',
      recipient: '+91-9876543216',
      message: 'Homework reminder: Complete mathematics assignment.',
      related_table: 'tasks',
      related_id: 'task-006',
      trigger_time: '2024-01-16T17:00:00Z',
      sent_at: null,
      status: 'Pending',
      created_at: '2024-01-15T16:00:00Z'
    },
    {
      id: 'alert-008',
      type: 'WhatsApp',
      recipient: '+91-9876543217',
      message: 'Health check: Time for weekly blood pressure monitoring.',
      related_table: 'tasks',
      related_id: 'task-005',
      trigger_time: '2024-01-16T08:00:00Z',
      sent_at: null,
      status: 'Pending',
      created_at: '2024-01-15T17:00:00Z'
    },
    {
      id: 'alert-009',
      type: 'WhatsApp',
      recipient: '+91-9876543218',
      message: 'Grocery shopping: Weekly shopping list is ready.',
      related_table: 'inventory',
      related_id: 'inv-006',
      trigger_time: '2024-01-16T10:00:00Z',
      sent_at: null,
      status: 'Pending',
      created_at: '2024-01-15T18:00:00Z'
    },
    {
      id: 'alert-010',
      type: 'WhatsApp',
      recipient: '+91-9876543219',
      message: 'Cultural reminder: Temple visit this Sunday.',
      related_table: 'activities',
      related_id: 'act-003',
      trigger_time: '2024-01-16T07:00:00Z',
      sent_at: null,
      status: 'Pending',
      created_at: '2024-01-15T19:00:00Z'
    }
  ],

  directory: [
    // Service Provider - Emergency
    {
      id: 'dir-001',
      name: 'City Hospital',
      type: 'Service Provider',
      category: 'Emergency',
      sub_category: 'Medical',
      phone: '+91-422-1234567',
      email: 'emergency@cityhospital.com',
      address: '123 Hospital Road, Coimbatore',
      location_lat: 11.0168,
      location_lng: 76.9558,
      rating: 4.5,
      notes: '24/7 emergency services, good cardiology department',
      last_contacted: '2024-01-10',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'dir-002',
      name: 'Coimbatore Fire Station',
      type: 'Service Provider',
      category: 'Emergency',
      sub_category: 'Fire',
      phone: '101',
      email: 'fire@coimbatore.gov.in',
      address: '456 Fire Station Road, Coimbatore',
      location_lat: 11.0268,
      location_lng: 76.9658,
      rating: 4.8,
      notes: 'Quick response time, professional service',
      last_contacted: '2023-12-15',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'dir-003',
      name: 'Police Station - Gandhipuram',
      type: 'Service Provider',
      category: 'Emergency',
      sub_category: 'Security',
      phone: '100',
      email: 'gandhipuram@police.tn.gov.in',
      address: '789 Police Station Road, Coimbatore',
      location_lat: 11.0068,
      location_lng: 76.9458,
      rating: 4.2,
      notes: 'Local police station, responsive to complaints',
      last_contacted: '2024-01-05',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'dir-004',
      name: 'Tamil Nadu Electricity Board',
      type: 'Service Provider',
      category: 'Emergency',
      sub_category: 'Electrical',
      phone: '1912',
      email: 'complaints@tneb.in',
      address: '101 Power Station, Coimbatore',
      location_lat: 11.0368,
      location_lng: 76.9758,
      rating: 3.8,
      notes: 'Government electricity department',
      last_contacted: '2024-01-08',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'dir-005',
      name: 'Coimbatore Water Supply',
      type: 'Service Provider',
      category: 'Emergency',
      sub_category: 'Plumbing',
      phone: '+91-422-2345678',
      email: 'water@coimbatore.gov.in',
      address: '202 Water Works, Coimbatore',
      location_lat: 11.0468,
      location_lng: 76.9858,
      rating: 4.0,
      notes: 'Municipal water supply department',
      last_contacted: '2023-11-20',
      created_at: '2024-01-01T00:00:00Z'
    },

    // Family Member - Personal
    {
      id: 'dir-006',
      name: 'Uncle Rajesh',
      type: 'Family Member',
      category: 'Emergency',
      sub_category: 'Relative',
      phone: '+91-9876543220',
      email: 'rajesh.uncle@email.com',
      address: '303 Family Street, Coimbatore',
      location_lat: 11.0568,
      location_lng: 76.9958,
      rating: 5.0,
      notes: 'Maternal uncle, doctor by profession, very helpful',
      last_contacted: '2024-01-12',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'dir-007',
      name: 'Aunty Meera',
      type: 'Family Member',
      category: 'Emergency',
      sub_category: 'Relative',
      phone: '+91-9876543221',
      email: 'meera.aunty@email.com',
      address: '404 Relative Lane, Coimbatore',
      location_lat: 11.0668,
      location_lng: 77.0058,
      rating: 4.9,
      notes: 'Paternal aunt, teacher, good with children',
      last_contacted: '2024-01-14',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'dir-008',
      name: 'Cousin Aravind',
      type: 'Family Member',
      category: 'Emergency',
      sub_category: 'Relative',
      phone: '+91-9876543222',
      email: 'aravind.cousin@email.com',
      address: '505 Cousin Road, Chennai',
      location_lat: 13.0827,
      location_lng: 80.2707,
      rating: 4.7,
      notes: 'Elder cousin, software engineer, technical help',
      last_contacted: '2024-01-09',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'dir-009',
      name: 'Grandpa Venkatesh',
      type: 'Family Member',
      category: 'Emergency',
      sub_category: 'Relative',
      phone: '+91-9876543223',
      email: 'venkatesh.grandpa@email.com',
      address: '606 Ancestor Street, Madurai',
      location_lat: 9.9252,
      location_lng: 78.1198,
      rating: 5.0,
      notes: 'Paternal grandfather, retired bank manager, financial advice',
      last_contacted: '2024-01-11',
      created_at: '2024-01-01T00:00:00Z'
    },
    {
      id: 'dir-010',
      name: 'Grandma Saraswati',
      type: 'Family Member',
      category: 'Emergency',
      sub_category: 'Relative',
      phone: '+91-9876543224',
      email: 'saraswati.grandma@email.com',
      address: '707 Elder Lane, Trichy',
      location_lat: 10.7905,
      location_lng: 78.7047,
      rating: 5.0,
      notes: 'Maternal grandmother, spiritual guide, traditional knowledge',
      last_contacted: '2024-01-13',
      created_at: '2024-01-01T00:00:00Z'
    }
  ]
};