#!/bin/bash

echo "==========================================="
echo "   Divine-Nest Xiaomi Installation Guide"
echo "==========================================="
echo ""
echo "✅ APK is ready and copied to: ./Divine-Nest-Xiaomi.apk"
echo "   Size: $(ls -lh Divine-Nest-Xiaomi.apk | awk '{print $5}')B"
echo ""
echo "📱 INSTALLATION STEPS FOR XIAOMI:"
echo ""
echo "1️⃣ ENABLE UNKNOWN SOURCES:"
echo "   Settings → Privacy protection → Special permissions"
echo "   → Install unknown apps → File Manager → Allow"
echo ""
echo "2️⃣ TRANSFER APK TO PHONE:"
echo "   📂 Option A - USB Cable:"
echo "      • Connect your Xiaomi phone to computer"
echo "      • Copy ./Divine-Nest-Xiaomi.apk to phone storage"
echo "      • Safely eject and disconnect"
echo ""
echo "   ☁️ Option B - Cloud Storage:"
echo "      • Upload Divine-Nest-Xiaomi.apk to Google Drive/Dropbox"
echo "      • Download on your Xiaomi phone"
echo ""
echo "3️⃣ INSTALL THE APP:"
echo "   • Open File Manager on your phone"
echo "   • Navigate to the APK file location"
echo "   • Tap Divine-Nest-Xiaomi.apk"
echo "   • Allow installation from unknown sources if prompted"
echo "   • Tap INSTALL and wait for completion"
echo ""
echo "4️⃣ LAUNCH & SETUP:"
echo "   • Find 'Divine Nest' in your app drawer"
echo "   • Tap to open the app"
echo "   • Complete the family setup wizard"
echo "   • Start using voice commands in Tamil/English!"
echo ""
echo "==========================================="
echo "🎯 APP FEATURES:"
echo "   • Voice Commands (Tamil & English)"
echo "   • Family Task Management"
echo "   • Meal Planning & Recipes"
echo "   • Finance Tracking"
echo "   • Cultural Features (Panchangam)"
echo "   • Offline Functionality"
echo "==========================================="
echo ""
echo "❗ XIAOMI NOTES:"
echo "   • You may need to disable MIUI optimization"
echo "   • Grant microphone, storage, location permissions"
echo "   • Allow unrestricted battery usage"
echo ""
read -p "Press Enter to continue..."